name: Generate README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Generate README.md
        run: npm run readme
      - name: Commit change
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "GitHub Action: generate README"
          git push
